# Generated by Django 4.2.6 on 2023-10-30 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(max_length=50)),
                ('timeOfOrder', models.DateField(auto_now_add=True)),
                ('size', models.IntegerField(choices=[(14, 'Large'), (12, 'Medium'), (8, 'Small')])),
                ('style', models.CharField(choices=[('HI', 'Hawaiian'), ('PE', 'Pepperoni'), ('CH', 'Cheese'), ('MT', 'Meat')], max_length=2)),
            ],
        ),
    ]
